_wandb:
    value:
        cli_version: 0.19.3
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 9
                - 55
                - 103
            "2":
                - 1
                - 9
                - 55
                - 103
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.3
            "8":
                - 5
                - 9
            "12": 0.19.3
            "13": linux-x86_64
